version: "3.3"

services:
  django_app:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./db:/db
      - ./backend:/backend:ro
    depends_on:
      - everytime_parser
    # environment:
    #   - VIRTUAL_HOST=api.dps0340.xyz

  everytime_parser:
    build:
      context: ./everytime-parse-api
    restart: always
    # environment:
    #   - VIRTUAL_HOST=everytime.dps0340.xyz
