version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

  django_app:
    build:
      context: ./backend
    networks:
      - app-tier
    restart: always
    volumes:
      - ./db:/db
      - ./backend:/backend:ro
    depends_on:
      - everytime_parser
    environment:
      - VIRTUAL_HOST=api.dps0340.xyz
      - VIRTUAL_PORT=8000

  everytime_parser:
    build:
      context: ./everytime-parse-api
    networks:
      - app-tier
    restart: always
    environment:
      - VIRTUAL_HOST=everytime.dps0340.xyz
      - VIRTUAL_PORT=8009

networks:
  app-tier:
    driver: bridge
